import { oracleScript, oracleScripts, oracleExecutable } from './oracle.ts';
import{readFileSync,writeFileSync,mkdirSync,readdirSync}from'node:fs';import{resolve}from'node:path';import{spawnSync}from'node:child_process';import{compareRuns}from'../../src/compare-runs.ts';import{hashLayout}from'../../src/determinism.ts';import{render}from'../../src/scoreboard-render.ts';
import { pluginRoot } from '../../src/runtime.ts';
import { normalize } from './evaluation.ts';
import { score } from '../../src/score-run.ts';
import { checkHash } from '../../src/determinism.ts';
const root=process.argv[2]??'/tmp/design-lab-p4-equivalence',oracle=oracleScript('evaluation-oracle.py'),results:any[]=[];
if(!root.startsWith('/tmp/'))throw new Error('scratch root must be under /tmp');
function py(request:any){const path=resolve(root,'aux-request.json');writeFileSync(path,JSON.stringify(request));const p=spawnSync(oracleExecutable,[oracle,path],{encoding:'utf8',env:{...process.env,PYTHONDONTWRITEBYTECODE:'1',DYLD_FALLBACK_LIBRARY_PATH:'/opt/homebrew/lib'}});if(p.status!==0)throw new Error(p.stderr);return p;}
function differences(a:any,b:any,p='',out:string[]=[]):string[]{if(out.length>25||Object.is(a,b))return out;if(!a||!b||typeof a!=='object'||typeof b!=='object'){out.push(p+': '+JSON.stringify(a)+' != '+JSON.stringify(b));return out;}for(const k of new Set([...Object.keys(a),...Object.keys(b)]))differences(a[k],b[k],p+'/'+k,out);return out;}
for(const[a,b]of[['definitive-03','definitive-05'],['definitive-05','massport']] as const){const run=resolve(root,a,'run'),other=resolve(root,b,'run'),out=resolve(root,'aux',a+'-'+b);mkdirSync(out,{recursive:true});py({action:'compare',run,other,out});const expected=JSON.parse(readFileSync(out+'/comparison.json','utf8')),actual=compareRuns(run,other);writeFileSync(out+'/comparison-ts.json',JSON.stringify(actual,null,2));results.push({operation:'compare',pair:[a,b],diffs:differences(expected,actual)});
 const folder=run+'/figma/trees',file=readdirSync(folder).filter(p=>p.endsWith('.json'))[0],layout=folder+'/'+file!;const hash=spawnSync(oracleExecutable,['-c',"import sys;sys.path.insert(0,sys.argv[1]);import determinism;print(determinism.hash_layout(sys.argv[2]))",oracleScripts,layout],{encoding:'utf8'}).stdout.trim();writeFileSync(out+'/expected.txt',hash);const check=checkHash(layout,out+'/expected.txt');results.push({operation:'determinism',pair:[a,b],layout,python:hash,typescript:check.actual,match:check.pass});
 py({action:'scorecard',run,compare:[other],out});const expectedCard=JSON.parse(readFileSync(out+'/scorecard.json','utf8')),actualCard=await score(run,{compare:[other]});for(const c of [expectedCard,actualCard]){delete c.generatedAt;delete c.sections.cost.clock.scorerSeconds;}results.push({operation:'score-repeatability',pair:[a,b],diffs:differences(normalize(expectedCard),normalize(actualCard))});
}
const rows=[{timestamp:'2026-10-07T00:00:00Z',site:'test',tier:2,pluginVersion:'0.23.2',pluginCommit:'abcdef12',coverage:{built:2,inventoried:3,buildable:3,ratio:2/3,placementShare:.25},correctedWidths:{pass:2,total:3,medianRatio:.02},originalWidths:{pass:1,total:3,medianRatio:.1},openFindings:{blocker:0,major:1,minor:2,other:0},tokens:{input:100,output:50,cacheRead:200,cacheWrite:10,total:360},time:{runner:{activeSeconds:83,steps:10},clock:{wallSeconds:3600},working:{status:'not-measured',reason:'missing'}}}];
const out=resolve(root,'aux','scoreboard');mkdirSync(out,{recursive:true});py({action:'scoreboard',run:resolve(root,'definitive-05/run'),out,rows});writeFileSync(out+'/report-ts.html',render(rows));results.push({operation:'scoreboard',match:readFileSync(out+'/report.html','utf8')===render(rows)});
writeFileSync(root+'/aux-summary.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));

process.exitCode=results.some(r=>r.match===false||r.diffs?.length)?1:0;
